---
- name: Play que valida o status dos nós do GPFS
  hosts: clienterhel[7-9].s2linux.local
  become: true
  gather_facts: true
  vars:
    ansible_password: 12345678
  tasks:
    - name: Valida o status no nó {{ inventory_hostname }}
      ansible.builtin.shell:
        cmd: "cat /root/gpfs_state.txt"
      register: saida_gpfs

    - name: Cria a variável que guardará o estado do GPFS
      ansible.builtin.set_fact:
        estado_gpfs: "{{ ((saida_gpfs.stdout | split('\n'))[2] | replace(' ', '') | split(':'))[1] }}"

    - name: Verifica se o nó está active
      ansible.builtin.assert:
        that: 'estado_gpfs == "active"'
        fail_msg: 'Nó {{ inventory_hostname }} não está com o status do GPFS como active'

- name: Play que valida se tem algum nó com o File System montado
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Valida se tem algum nó com o File System montado
      ansible.builtin.assert:
        that: >
          - ('/var/fs_application' in hostvars['clienterhel7.s2linux.local'].ansible_facts.mounts | map(attribute='mount')) or
            ('/var/fs_application' in hostvars['clienterhel8.s2linux.local'].ansible_facts.mounts | map(attribute='mount')) or
            ('/var/fs_application' in hostvars['clienterhel9.s2linux.local'].ansible_facts.mounts | map(attribute='mount'))
        fail_msg: "/var/fs_application não está montado em lugar nenhum"
...
