---
- name: Play que testa se um processo está no ar ou não
  hosts: clienterhel7.s2linux.local
  gather_facts: true
  become: false
  tasks:
    - name: Verifica se o processo do rsyslogd está no ar
      community.general.pids:
        name: rsyslogd
        ignore_case: true
      register: lista_processos
      when: false

    - name: Exibe uma mensagem dizendo se está ou não
      ansible.builtin.assert:
        that: lista_processos.pids | length == 0
        fail_msg: Processo do rsyslogd está no ar
        success_msg: Processo do rsyslogd fora
      when: false

    - name: Exemplo para o Diego
      ansible.builtin.assert:
        that: >
          (ansible_mounts | selectattr('mount', 'equalto', '/opt'))[0].size_available > 5368709120 and
          (ansible_mounts | selectattr('mount', 'equalto', '/tmp'))[0].size_available > 1073741824
        fail_msg: O /tmp e/ou o /opt possui espaço em disco insuficiente
        success_msg: O /tmp e o /opt possuem espaço em disco suficiente

...
