---
# Playbook que verifica se o servidor está vulnerável à falha relatada no boletin RHSB-2024-002
# https://access.redhat.com/security/vulnerabilities/RHSB-2024-002
# Desenvolvido por Roger Príncipe

- name: Play verificador de vulnerabilidade (cups)
  hosts: clienterhel7.s2linux.local
  gather_facts: false
  tasks:
    - name: Coleta os facts relacionados aos pacotes instalados na máquina
      ansible.builtin.package_facts:
        manager: auto

    - name: Coleta os facts relacionados aos serviços da máquina
      ansible.builtin.service_facts:

    - name: Bloco onde se verifica a ocorrência da vulnerabilidade
      block:
        - name: Verifica se um dos pacotes está instalado
          ansible.builtin.assert:
            that: >
              'cups' not in ansible_facts.packages.keys() and
              'cups-filters' not in ansible_facts.packages.keys()
            success_msg: Sistema não está vulnerável
      rescue:
        - name: Captura o conteúdo do arquivo /etc/cups/cups-browsed.conf
          ansible.builtin.slurp:
            src: /etc/cups/cups-browsed.conf
          register: cupsbrowsed_conf

        - name: Cria o retorno da busca pelo parâmetro BrowseRemoteProtocols em cups-browsed.conf
          ansible.builtin.set_fact:
            retorno_cupsbrowsed_conf: "{{ cupsbrowsed_conf['content'] | b64decode | regex_search('^BrowseRemoteProtocols.*cups.*', multiline=true)}}"

        - name: Caso o parâmetro BrowseRemoteProtocols esteja com cups, verifica se o serviço está no ar ou habilitado no boot
          when: retorno_cupsbrowsed_conf | length > 0
          ansible.builtin.assert:
            that: >
              ansible_facts.services['cups-browsed.service'].state != 'running' and ansible_facts.services['cups-browsed.service'].status != 'enabled'
            success_msg: Sistema não está vulnerável
            fail_msg: Sistema vulnerável ou potencialmente vulnerável. Verifique.
