- hosts: clienterhel8.s2linux.local
  become: true
  gather_facts: false
  tasks:
    - shell: yum -q repolist | grep -Eiv "^repo id"
      register: yum_repolist

    - shell: subscription-manager repos --list-enabled | grep -E "^Repo ID"
      register: subsc_man

    - debug:
        msg: Executar Zabbix Sender
      when: yum_repolist.stdout_lines | length == subsc_man.stdout_lines | length
