---

- name: Teste
  hosts: localhost
  strategy: free
  gather_facts: true
  force_handlers: true
  become: true
  tasks:
    - name: Teste
      ansible.builtin.debug:
        msg: "Usuário: {{ lookup('env', 'VMWARE_USER') }}; Senha: {{ lookup('env', 'VMWARE_USER') }}"
...
