---
- name: Play de teste
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Teste
      ansible.builtin.set_fact:
        meuhost: "{{ host_recebido }}"

    - name: Bloco que testa se {{ meuhost }} é de fato um IP
      block:
        - name: Testa se {{ meuhost }} é um IP
          ansible.builtin.assert:
            that: meuhost | ansible.utils.ipaddr == false
            fail_msg: "O usuário deve ter digitado um IP. Vamos tentar arrumar"

      rescue:
        - name: Resignifica a variável do host para um FQDN
          ansible.builtin.set_fact:
            meuhost: "{{ lookup('community.general.dig', meuhost + '/PTR') }}"

    - name: Exibe o certo
      ansible.builtin.debug:
        var: meuhost

