---
- hosts: localhost
  vars:
    variavel: "Roger\t\nRoger\nRoger\r\tAAAA"
  tasks:
    - register: aaa
      ansible.builtin.shell: echo -e "{{ variavel }}"

    - ansible.builtin.debug:
        var: aaa
