- hosts: clienterhel8.s2linux.local
  gather_facts: true
  tasks:
    - shell: yum -q repolist | grep -iv "repo id"
      register: yum_repolist

    - shell: subscription-manager repos --list-enabled | grep -E "^Repo ID"
      register: subsc_man

    - shell: zabbix_sender
      when: yum_repolist.stdout_lines | length > subsc_man.stdout_lines | length
