---
- name: Play de teste
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Bloco que testa se {{ host_recebido }} é de fato um IP
      block:
        - name: Teste
          ansible.builtin.assert:
            that: host_recebido | ansible.utils.ipaddr == false
            fail_msg: "O usuário deve ter digitado um IP. Vamos tentar arrumar"

      rescue:
        - name: Resignifica a variável do host para um FQDN
          ansible.builtin.set_fact:
            host_recebido_fqdn: "{{ lookup('community.general.dig', host_recebido + '/PTR') }}"

      always:
        - name: Exibe o certo
          ansible.builtin.debug:
            var: host_recebido_fqdn

