---
- hosts: localhost
  gather_facts: false
  tasks:
    - community.dns.nameserver_info:
        name:
          - www.uol.com.br
      register: result

    - name: Show nameservers for www.example.com
      ansible.builtin.debug:
        msg: "{{ result }}"
