---
- hosts: localhost
  connection: local
  vars:
    meu_servidor: webserver.dominio.com.br
  tasks:
    - debug:
        msg: Com domínio: {{ meu_servidor }}

    - debug:
        msg: Sem domínio: {{ meu_servidor | regex_replace('.dominio.com.br$') }}

