---
- hosts: localhost
  connection: local
  vars:
    meu_servidor: webserver.dominio.com.br
  tasks:
    - ansible.builtin.debug:
        msg: "Com domínio: {{ meu_servidor }}"

    - ansible.builtin.debug:
        msg: "Sem domínio: {{ meu_servidor | regex_replace('.dominio.com.br$') }}"
