---
- name: Play verificador de vulnerabilidade
  hosts: clienterhel7.s2linux.local
  gather_facts: false
  tasks:
    - name: Coleta os facts relacionados aos pacotes instalados na máquina
      ansible.builtin.package_facts:
        manager: auto

    - name: mostra
      ansible.builtin.assert:
        that: >
          "'cups' not in ansible_facts.packages.keys()" or
          "'cups-filters' not in ansible_facts.packages.keys()"
        fail_msg: Ruim
        success_msg: Bom


          #    - name: Verifica se os pacotes sucetíveis à vulnerabilidade estão instalados
