---
- name: Play que testa se um processo está no ar ou não
  hosts: clienterhel7.s2linux.local
  gather_facts: true
  become: false
  tasks:
    - name: Verifica se o processo do rsyslogd está no ar
      community.general.pids:
        name: rsyslogd
        ignore_case: true
      register: lista_processos
      when: false

    - name: Exibe uma mensagem dizendo se está ou não
      ansible.builtin.assert:
        that: lista_processos.pids | length == 0
        fail_msg: Processo do rsyslogd está no ar
        success_msg: Processo do rsyslogd fora
      when: false

    - name: Mostra
      ansible.builtin.debug:
        var: ansible_facts['mounts'] | selectattr('mount', 'equalto', '/boot') 
...
