---
- hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.setup:
        gather_subset:
          - "!all,!min"
          - local

    - ansible.builtin.debug:
        var: ansible_facts['distribution_major_version']
