---
- hosts: clienterhel7.s2linux.local
  gather_facts: false
  become: false
  tasks:
    - name: Verifica se o processo do DB2 está no ar
      community.general.pids:
        name: db2
        ignore_case: true
      register: lista_processos

    - name: Exibe uma mensagem dizendo se está ou não
      ansible.builtin.assert:
        that: lista_processos.pids | length == 0
        fail_msg: Processo do DB2 está no ar
        success_msg: Processo do DB2 fora
...
