---
- hosts: clienterhel8.s2linux.local
  become: true
  gather_facts: false
  tasks:
    - register: yum_repolist
      ansible.builtin.shell: yum -q repolist | grep -Eiv "^repo id"

    - register: subsc_man
      ansible.builtin.shell: subscription-manager repos --list-enabled | grep -E "^Repo ID"

    - when: yum_repolist.stdout_lines | length == subsc_man.stdout_lines | length
      ansible.builtin.debug:
        msg: Executar Zabbix Sender
