---
- name: Play verificador de vulnerabilidade
  hosts: clienterhel7.s2linux.local
  gather_facts: false
  tasks:
    - name: Coleta os facts relacionados aos pacotes instalados na máquina
      ansible.builtin.package_facts:
        manager: auto

    - name: Coleta os facts relacionados aos serviços da máquina
      ansible.builtin.service_facts:

    - name: Teste
      debug:
        var: ansible_facts.services

    - name: Bloco onde se verifica a ocorrência da vulnerabilidade
      block:
        - name: mostra
          ansible.builtin.assert:
            that: >
              'cups' not in ansible_facts.packages.keys() and
              'cups-filters' not in ansible_facts.packages.keys()
            success_msg: Sistema não está vulnerável
      rescue:
        - name: Captura o conteúdo do arquivo /etc/cups/cups-browsed.conf
          ansible.builtin.slurp:
            src: /etc/cups/cups-browsed.conf
          register: cupsbrowsed_conf

        - name: Caso o parâmetro BrowseRemoteProtocols esteja com cups, verifica se o serviço está no ar ou habilitado no boot
          when: cupsbrowsed_conf['content'] | b64decode | regex_search('^BrowseRemoteProtocols.*cups.*') != ""
          debug:
            msg: "{{ cupsbrowsed_conf['content'] | b64decode | regex_search('^BrowseRemoteProtocols.*cups.*') }}"
            #          ansible.builtin.assert:
            #            that: >
            #              ansible_facts.services['cups-browsed.service'].state == 'running' or
            #              ansible_facts.services['cups-browsed.service'].status == 'enabled'
...
