---

- name: Teste
  hosts: localhost
  become: true
  gather_facts: false
  vars:
    arq_compressed: compressed.tar.gz
  tasks:
    - name: Cria
      ansible.builtin.shell: "mkdir -p /root/diretorio_caotico/asdf; touch /root/diretorio_caotico/asdf/aaaa; pwd"
      register: aaaa

    - name: Compacta o conteúdo de um diretório
      ansible.builtin.archive:
        path: /root/diretorio_caotic*
        dest: "{{ arq_compressed }}"
        format: gz
        force_archive: true
      register: teste_var

    - name: Mostra
      ansible.builtin.debug:
        msg: "{{ teste_var }}{{ aaaa }}"
