---

- name: Teste
  hosts: localhost
  become: true
  gather_facts: false
  vars:
    arq_compressed: compressed.tar.gz
  tasks:
    - name: Cria
      ansible.builtin.shell: "mkdir -p /runner/project/exemplo_pro_regis/asdf; touch /root/diretorio_caotico/asdf/aaaa; pwd"
      register: saida_module_shell

    - name: Compacta o conteúdo de um diretório
      ansible.builtin.archive:
        path: /root/diretorio_caotic*
        dest: "{{ arq_compressed }}"
        format: gz
        force_archive: true
      register: teste_var

    - name: Mostra saida modulo archive
      ansible.builtin.debug:
        msg: "{{ saida_modulo_archive }}"
         
    - name: Mostra saida modulo shell
      ansible.builtin.debug:
        msg: "{{ saida_modulo_shell }}"
