- hosts: clienterhel8.s2linux.local
  gather_facts: false
  tasks:
    - debug:
        msg: Variável {{ nhonho }}

    - name: Disable all RHSM repositories
      community.general.rhsm_repository:
        name: '*'
        state: disabled
