---
- name: Lista os DNS configurados na conexão {{ item }}
  ansible.builtin.shell: nmcli --fields ipv4.dns connection show {{ item }}
  register: saida_nmcli_mostra_conexoes

- name: Alimenta a lista criada anteriormente com as conexões com DNS configurado
  ansible.builtin.set_fact:
    conexoes_nm_com_dns: "{{ conexoes_nm_com_dns + [item] }}"
  when: "(saida_nmcli_mostra_conexoes.stdout | replace(' ', '') | split(':'))[1] != '--'"
...
