download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/dellemc-powermax-3.1.0.tar.gz
format_version: 1.0.0
name: powermax
namespace: dellemc
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.1.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/dellemc/powermax/versions/3.1.0/
