---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Executa o comando date
      ansible.builtin.shell: date
      environment:
        TZ: America/Sao_Paulo
      register: variavel_saida_shell

    - name: Mostra o conteúdo da saída do comando date
      ansible.builtin.debug:
        var: variavel_saida_shell.stdout
